CREATE TABLE ESTADO (
  ID_ESTADO SERIAL  NOT NULL ,
  DESCRICAO VARCHAR(255)      ,
PRIMARY KEY(ID_ESTADO));




CREATE TABLE REFEICAO (
  ID_REFEICAO SERIAL  NOT NULL ,
  HORARIO VARCHAR(5)    ,
  DESCRICAO INTEGER    ,
  OBSERVACAO VARCHAR(255)      ,
PRIMARY KEY(ID_REFEICAO));




CREATE TABLE ALIMENTO (
  ID_ALIMENTO SERIAL  NOT NULL ,
  DESCRICAO VARCHAR(255)    ,
  QUANTIDADE INTEGER    ,
  MEDIDA VARCHAR(150)      ,
PRIMARY KEY(ID_ALIMENTO));




CREATE TABLE CIDADE (
  ID_CIDADE SERIAL  NOT NULL ,
  ESTADO_ID_ESTADO INTEGER   NOT NULL ,
  DESCRICAO VARCHAR(255)      ,
PRIMARY KEY(ID_CIDADE),
  FOREIGN KEY(ESTADO_ID_ESTADO)
    REFERENCES ESTADO(ID_ESTADO)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX IFK_Rel_01 ON CIDADE (ESTADO_ID_ESTADO);


CREATE TABLE REFEICAO_ALIMENTO (
  ID_REFEICAO INTEGER   NOT NULL ,
  ID_ALIMENTO INTEGER   NOT NULL ,
  ID SERIAL  NOT NULL   ,
PRIMARY KEY(ID_REFEICAO, ID_ALIMENTO),
  FOREIGN KEY(ID_REFEICAO)
    REFERENCES REFEICAO(ID_REFEICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(ID_ALIMENTO)
    REFERENCES ALIMENTO(ID_ALIMENTO)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX IFK_Rel_05 ON REFEICAO_ALIMENTO (ID_REFEICAO);
CREATE INDEX IFK_Rel_06 ON REFEICAO_ALIMENTO (ID_ALIMENTO);


CREATE TABLE PACIENTE (
  ID_PACIENTE SERIAL  NOT NULL ,
  CIDADE_ID_CIDADE INTEGER   NOT NULL ,
  DATA_NASCIMENTO DATE    ,
  SEXO CHAR    ,
  EMAIL VARCHAR(45)    ,
  TELEFONE VARCHAR(20)    ,
  CELULAR VARCHAR(20)    ,
  ESTADO_CIVIL INTEGER    ,
  OCUPACAO VARCHAR(60)    ,
  CPF VARCHAR(10)    ,
  CEP VARCHAR(10)    ,
  ENDERECO VARCHAR(200)    ,
  NUMERO VARCHAR(10)    ,
  COMPLEMENTO VARCHAR(30)    ,
  BAIRRO VARCHAR(45)    ,
  OBSERVACAO VARCHAR(255)      ,
PRIMARY KEY(ID_PACIENTE),
  FOREIGN KEY(CIDADE_ID_CIDADE)
    REFERENCES CIDADE(ID_CIDADE));


CREATE INDEX IFK_Rel_03 ON PACIENTE (CIDADE_ID_CIDADE);


CREATE TABLE AVALIACAO_ANTROPOMETRICA (
  ID_AVALIACAO SERIAL  NOT NULL ,
  PACIENTE_ID_PACIENTE INTEGER   NOT NULL ,
  DATA_CADASTRO DATE    ,
  IDADE INTEGER    ,
  PESO DOUBLE PRECISION    ,
  PERC_GORDURA DOUBLE PRECISION    ,
  GORD_ABSOLUTA DOUBLE PRECISION    ,
  MASSA_MAGRA DOUBLE PRECISION    ,
  CIRCUNF_CINTURA DOUBLE PRECISION    ,
  CIRCUNF_ABDOMEN DOUBLE PRECISION    ,
  CIRCUNF_TORAX DOUBLE PRECISION    ,
  CIRCUNF_BRACO DOUBLE PRECISION    ,
  CIRCUNF_BRACO_CONTR DOUBLE PRECISION    ,
  CIRCUNF_COXA DOUBLE PRECISION    ,
  DOBRA_TRICEPS DOUBLE PRECISION    ,
  DOBRA_SUBESCAPULAR DOUBLE PRECISION    ,
  DOBRA_AXILAR_MED DOUBLE PRECISION    ,
  DOBRA_SUPRAILIACA DOUBLE PRECISION    ,
  DOBRA_ABDOMEN DOUBLE PRECISION    ,
  DOBRA_PEITORAL DOUBLE PRECISION    ,
  DOBRA_COXA DOUBLE PRECISION      ,
PRIMARY KEY(ID_AVALIACAO),
  FOREIGN KEY(PACIENTE_ID_PACIENTE)
    REFERENCES PACIENTE(ID_PACIENTE)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX IFK_Rel_02 ON AVALIACAO_ANTROPOMETRICA (PACIENTE_ID_PACIENTE);


CREATE TABLE PLANO_ALIMENTAR (
  ID_PLANO SERIAL  NOT NULL ,
  PACIENTE_ID_PACIENTE INTEGER   NOT NULL ,
  DESCRICAO VARCHAR(255)      ,
PRIMARY KEY(ID_PLANO, PACIENTE_ID_PACIENTE),
  FOREIGN KEY(PACIENTE_ID_PACIENTE)
    REFERENCES PACIENTE(ID_PACIENTE)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX IFK_Rel_04 ON PLANO_ALIMENTAR (PACIENTE_ID_PACIENTE);



